/**
 * O12KR1 · AI Degradation Strategy (Phase 3)
 * 预算超阈值时的降级处理：R2 占位写入 + Supabase 标记
 */

// ===========================
// Env 接口
// R2Bucket 类型来自 worker-configuration.d.ts（wrangler types 生成）
// ===========================
interface AiDegradationEnv {
  csnews_raw: {
    put(key: string, value: string | ArrayBuffer, options?: { httpMetadata?: { contentType?: string } }): Promise<void>;
    get(key: string): Promise<{ text(): Promise<string> } | null>;
    list(options?: { prefix?: string }): Promise<{ objects: { key: string }[] }>;
  };
  SUPABASE_URL: string;
  SUPABASE_SERVICE_KEY: string;
}
import { logEvent } from './log';

type DegradationLevel = 'L4' | 'L5' | 'L6';

// ===========================
// 降级说明
// ===========================

/**
 * 各层级的降级说明（供调用方展示 / 写入日志）
 */
function getDegradationMessage(level: DegradationLevel): string {
  switch (level) {
    case 'L4':
      return 'AI budget exceeded — async LLM analysis skipped, manual review needed';
    case 'L5':
      return 'AI budget exceeded — fission LLM report skipped, using keyword + bge-m3 similarity fallback';
    case 'L6':
      return 'AI budget exceeded — knowledge engine LLM skipped, retry next day';
  }
}

// ===========================
// Supabase 工具
// ===========================
function supabaseFetch(env: AiDegradationEnv, path: string, options?: RequestInit): Promise<Response> {
  const host = `https://${env.SUPABASE_URL}.supabase.co`;
  return fetch(`${host}${path}`, {
    ...options,
    headers: {
      'apikey': env.SUPABASE_SERVICE_KEY,
      'Authorization': `Bearer ${env.SUPABASE_SERVICE_KEY}`,
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });
}

// ===========================
// R2 占位写入
// ===========================

/**
 * 写 AI 降级占位文件到 R2
 *
 * @param warningId  预警记录 ID（来自 Supabase warnings 表）
 * @param level      降级层级
 * @param neuronsUsed  写文件时的 Neurons 当量（可选）
 * @param extraMeta  额外元数据（可选）
 */
export async function writeDegradedInsight(
  warningId: string,
  level: DegradationLevel,
  env: AiDegradationEnv,
  neuronsUsed?: number,
  extraMeta?: Record<string, unknown>,
): Promise<string> {
  const date = new Date().toISOString().slice(0, 10); // YYYY-MM-DD UTC
  const key = `ai-degraded/${date}/${warningId}.md`;

  const message = getDegradationMessage(level);
  const ts = new Date().toISOString();

  const content = [
    `# AI Degradation Report`,
    ``,
    `**Level**: ${level}`,
    `**Warning ID**: ${warningId}`,
    `**Triggered At**: ${ts}`,
    `**Degradation Message**: ${message}`,
    neuronsUsed !== undefined ? `**Neurons Used (at trigger)**: ${neuronsUsed}` : '',
    ``,
    `## Detail`,
    ``,
    message,
    ``,
    extraMeta ? `## Extra Metadata\n\`\`\`json\n${JSON.stringify(extraMeta, null, 2)}\n\`\`\`\n` : '',
    `---`,
    `> This file is auto-generated by O12KR1 AI Budget Tracking.`,
    `> Generated by csnews-agent.`,
  ]
    .filter(line => line !== '')
    .join('\n');

  await env.csnews_raw.put(key, content, {
    httpMetadata: { contentType: 'text/markdown; charset=utf-8' },
  });

  return key;
}

// ===========================
// Supabase 标记
// ===========================

/**
 * 在 Supabase 表中标记指定记录为 degraded
 *
 * 支持的表：
 * - `warnings`：预警记录（O12KR13 异步 AI 分析降级）
 * - `fission_searches`：裂变搜索记录（O7KR1 裂变降级）
 * - `knowledge`：知识库记录（O10KR1 Knowledge Engine 降级）
 *
 * @param recordId  待标记的记录 ID
 * @param table    目标表名（warnings | fission_searches | knowledge）
 */
export async function markAsDegraded(
  recordId: string,
  table: 'warnings' | 'fission_searches' | 'knowledge',
  env: AiDegradationEnv,
): Promise<boolean> {
  try {
    const res = await supabaseFetch(env, `/rest/v1/${table}?id=eq.${recordId}`, {
      method: 'PATCH',
      headers: { 'Prefer': 'return=minimal' },
      body: JSON.stringify({
        degraded: true,
        degraded_at: new Date().toISOString(),
      }),
    });

    if (!res.ok) {
      await logEvent((env as any), 'error', `[ai-degradation] PATCH ${table} failed: ${res.status} ${await res.text()}`, undefined, 'ai');;
      return false;
    }

    return true;
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    await logEvent((env as any), 'error', `[ai-degradation] markAsDegraded error: ${msg}`, undefined, 'ai');;
    return false;
  }
}
